baseurl = "http://shirtlah.com/"
languageCode = "en-SG"
title = "Shirt Lah!"
theme = "casper"
paginate = 3
DisqusShortname = "shirtlah"

[params]
  description = "Shirts for Singlish fans"
  logo = "images/shirtlah-logo-120x120.png"
  favicon = "images/shirtlah-logo-120x120.png"
  appleTouchIcon = "images/shirtlah-logo-120x120.png"
  cover = "images/cover.png"
  author = "shirtlah"
  twitterName = "shirtlah"
  facebookName = "shirtlah"
  instagramName = "shirtlah"
  pinterestName = "shirtlah"
  googlePlusName = "ShirtLah"
  authorlocation = "Singapore, Singapore"
  googleAnalyticsUserID = "UA-37884921-7"
  hideHUGOSupport = true
  paginatedSections = "post for team"
  customFooterPartial = "customFooter.html"
  customHeaderPartial = "customHeader.html"
  mailchimpUser = "0131f52df4a6540da5b6fd8a8"
  mailchimpId = "483f7dce00"
  mailchimpLabelText = "Wanna get a *Shirt Lah!* or, just *love* Singlish?"
  mailchimpLabelSubText = "Sign up for our **free** newsletter, and you'll get fun **Singlish** stuff. You'll also hear about Shirt Lah! news **before** everybody else. There'll also be **exclusive T-shirt give-aways**, so dun say we *bo jio* ah!"
  mailchimpButtonText = "Gimme lah!"

[permalinks]
  post = "/post/:slug/"
  for = "/for/:slug/"
  team = "/team/:slug/"
  design = "/design/:slug/"
  alphabet = "/singlish-alphabet/:slug/"

[[menu.main]]
  pre = "<h3>Follow</h3>"
  name = "Twitter"
  identifier = "social-twitter"
  weight = 3010
  url = "https://twitter.com/shirtlah"

[[menu.main]]
  name = "Facebook"
  identifier = "social-facebook"
  weight = 3020
  url = "https://facebook.com/shirtlah"

[[menu.main]]
  name = "Instagram"
  identifier = "social-instagram"
  weight = 3030
  url = "https://instagram.com/shirtlah"

[[menu.main]]
  name = "Pinterest"
  identifier = "social-pinterest"
  weight = 3040
  url = "https://pinterest.com/shirtlah"

[[menu.main]]
  name = "Google+"
  identifier = "social-google-plus"
  weight = 3040
  url = "https://google.com/+ShirtLah"
