baseurl = "http://shirtlah.com/"
languageCode = "en-SG"
title = "Shirt Lah!"
theme = "casper"
paginate = 3
DisqusShortname = "shirtlah"

[params]
  description = "Shirts for Singlish fans"
  cover = "images/cover.png"
  author = "shirtlah"
  twitterName = "shirtlah"
  facebookName = "shirtlah"
  instagramName = "shirtlah"
  googlePlusName = "ShirtLah"
  authorlocation = "Singapore, Singapore"
  googleAnalyticsUserID = "UA-37884921-7"
  hideHUGOSupport = true
  paginatedSections = "post for"
  customFooterPartial = "customFooter.html"
  customHeaderPartial = "customHeader.html"
  mailchimpU = "0131f52df4a6540da5b6fd8a8"
  mailchimpId = "483f7dce00"
  mailchimpLabelText = "I wanna Shirt Lah!"
  mailchimpButtonText = "Jio me!"

[permalinks]
  post = "/post/:slug/"
  for = "/for/:slug/"
  design = "/design/:slug/"

[[menu.main]]
  name = "Home"
  weight = -1000
  identifier = "main-home"
  url = "/"

[[menu.main]]
  pre = "<h3>Follow</h3>"
  name = "Twitter"
  identifier = "social-twitter"
  weight = 3010
  url = "https://twitter.com/shirtlah"

[[menu.main]]
  name = "Facebook"
  identifier = "social-facebook"
  weight = 3020
  url = "https://facebook.com/shirtlah"
